version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto
    tty: true
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/conf:/mosquitto/conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log