version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/config/:/mosquitto/config/:ro #remove :ro for create new user and add again for run
      - ./mosquitto/log/:/mosquitto/log/
      - ./mosquitto/data/:/mosquitto/data/
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped